### ISSUE TITLE
pysmt solvers on osx

### ISSUE THREAD

**Issue by phanrahan** [pysmt/pysmt#249]
I am having trouble installing z3 and matsat on my mac osx system.

For example, 

% pysmt-install --z3

fails with the following. 

% pysmt-install --z3
This script allows you to install the solvers supported by pySMT.

By executing this script, you confirm that you have read and agreed
with the licenses of each solver.

Notice: the installation process might require building tools
        (e.g., make and gcc).

Continue? [Y]es/[N]o: Y
Traceback (most recent call last):
  File "/usr/local/bin/pysmt-install", line 11, in <module>
    sys.exit(main())
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/install.py", line 211, in main
    installer.install(force_redo=options.force_redo)
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/installers/base.py", line 126, in install
    if (not force_redo) and self.is_installed():
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/installers/base.py", line 141, in is_installed
    ver = self.get_installed_version()
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/installers/z3.py", line 67, in get_installed_version
    (major, minor, ver, _) = z3.get_version()
AttributeError: module 'z3' has no attribute 'get_version'

Are their instructions on how to install solvers on osx?

**Comment by marcogario** [comment]
Support for install.py under OS X is still underway. Can you please checkout the branch https://github.com/pysmt/pysmt/tree/macosx_installers  and try to use the install.py that is there? 

This should support Z3 (4.4.1) and MathSAT (5.3.9), although you are required to have the latest version of OS X to run the MathSAT python bindings.  Other solvers are not supported yet by install.py. However, you can try to install the solvers manually (without using install.py), as long as you configure the PYTHONPATH correctly, pySMT should be able to see them.

Let us know if you run into any problem. Thanks for using pySMT.

**Comment by phanrahan** [comment]
I tried that and it doesn't work on my machine. I am running 10.11.4

```
% git status
On branch macosx_installers
Your branch is up-to-date with 'origin/macosx_installers'.

% python3 install.py --z3
This script allows you to install the solvers supported by pySMT.

By executing this script, you confirm that you have read and agreed
with the licenses of each solver.

Notice: the installation process might require building tools
        (e.g., make and gcc).

Continue? [Y]es/[N]o: Y
Traceback (most recent call last):
  File "install.py", line 18, in <module>
    pysmt.cmd.install.main()
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/install.py", line 210, in main
    installer.install(force_redo=options.force_redo)
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/installers/base.py", line 129, in install
    if (not force_redo) and self.is_installed():
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/installers/base.py", line 144, in is_installed
    ver = self.get_installed_version()
  File "/Users/hanrahan/git/pysmt/pysmt/cmd/installers/z3.py", line 72, in get_installed_version
    (major, minor, ver, _) = z3.get_version()
AttributeError: module 'z3' has no attribute 'get_version'
```

**Comment by marcogario** [comment]
I am glad that you managed to solve. Unfortunately, I am not able to reproduce. I extended the testing for OS X for python 3, and it works as expected. Thanks for reporting it.
