### ISSUE TITLE
CVC4 BitVector Wrapper cannot deal with long constants 

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#265]
The python wrapper does not seem to distinguish between the two constructor for BitVectors in which the value is expressed as a ```long```.

In the example that we added ```small_set/QF_ABV/com.galois.ecc.P384ECC64.group_add6.short.smt2``` there is a constant bitvector that requires a long to be represented. When translating it for CVC, we get:
```
Traceback (most recent call last):
  File "pysmt/cmd/shell.py", line 149, in <module>
    main()
  File "pysmt/cmd/shell.py", line 145, in main
    shell.main()
  File "pysmt/cmd/shell.py", line 137, in main
    self.smtlib_solver(input_stream)
  File "pysmt/cmd/shell.py", line 121, in smtlib_solver
    r = evaluate_command(cmd, solver)
  File "/home/viashino/pySMT/github/pysmt/smtlib/script.py", line 271, in evaluate_command
    return solver.assert_(cmd.args[0])
  File "/home/viashino/pySMT/github/pysmt/solvers/smtlib.py", line 313, in assert_
    return self.add_assertion(expr, named)
  File "/home/viashino/pySMT/github/pysmt/solvers/cvc4.py", line 80, in add_assertion
    term = self.converter.convert(formula)
  File "/home/viashino/pySMT/github/pysmt/decorators.py", line 84, in catch_conversion_error_wrap
    res = f(*args, **kwargs)
  File "/home/viashino/pySMT/github/pysmt/solvers/cvc4.py", line 213, in convert
    return self.walk(formula)
  File "/home/viashino/pySMT/github/pysmt/walkers/dag.py", line 106, in walk
    res = self.iter_walk(formula, **kwargs)
  File "/home/viashino/pySMT/github/pysmt/walkers/dag.py", line 98, in iter_walk
    self._process_stack(**kwargs)
  File "/home/viashino/pySMT/github/pysmt/walkers/dag.py", line 91, in _process_stack
    self._compute_node_result(formula, **kwargs)
  File "/home/viashino/pySMT/github/pysmt/walkers/dag.py", line 75, in _compute_node_result
    self.memoization[key] = f(formula, args=args, **kwargs)
  File "/home/viashino/pySMT/github/pysmt/solvers/cvc4.py", line 306, in walk_bv_constant
    cvc4_bv = CVC4.BitVector(width, value)
  File "/home/viashino/.smt_solvers/python_bindings/CVC4.py", line 1203, in __init__
    this = _CVC4.new_BitVector(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_BitVector'.
  Possible C/C++ prototypes are:
    CVC4::BitVector::BitVector(unsigned int,CVC4::Integer const &)
    CVC4::BitVector::BitVector(unsigned int)
    CVC4::BitVector::BitVector()
    CVC4::BitVector::BitVector(unsigned int,unsigned long)
    CVC4::BitVector::BitVector(unsigned int,CVC4::BitVector const &)
    CVC4::BitVector::BitVector(std::string const &,unsigned int)
    CVC4::BitVector::BitVector(std::string const &)
```

My understanding is that the method ```CVC4::BitVector::BitVector(unsigned int,unsigned long)``` is not being wrapped.

**Comment by marcogario** [comment]
Fixed in PR #309
