### ISSUE TITLE
Windows: Solver Installation (pysmt-install) 

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#328]
This issue is to keep track of the status of support of Microsoft Windows (win from now on).
Each solver should be tested on win and, if it works, the installer (pysmt-install) should be able to build the solver and python binding. Finally, the CI should be extended to run the tests for the solver.
CI is done using appveyor. See the folder ```ci/appveyor``` for details.

Current situation:

* MathSAT: Unknown (but really should)
* Z3: Unknown (but really should)
* CVC4: Unknown
* Picosat: Unknown
* CUDD: Unknown
* Yices: Unknown

Steps to go from "Unknown" to "Tested on CI":

* Check on the documentation of the solver, whether it is known to work (or not work) with Win. If it should work, try to compile it and build the python bindings. If it works, please comment on this issue about the steps needed to get it to work (in some cases this is trivial, in some other cases it requires some tweaking). Please, include a list of the dependencies needed to make the installer work.
*Note*: We are interested in native support. If there is no other alternative, we might consider using MinGW or similar.

* Extend Installer (pysmt-install/ pysmt/cmd/installers/<solver>.py) to work on Win. Adapt the existing code to work on Win, and perform the steps described above. Open a PR against master once this is working. This will test that the installer still works on Linux (via Travis CI).
    Note: pysmt-install should not worry about installing dependencies, but please clearly state if there is some crucial dependency to be installed beforehand.

* Setup CI for Win: Once pysmt-install works, modify the scripts in ```ci/appveyor```to install all the dependencies needed by pysmt-install to work, and run the tests. Open a PR once this is working.

**Comment by marcogario** [comment]
Z3 Support added in PR #385. Look there to see what kind of changes might be involved.

**Comment by KritikaA** [comment]
Hi,
I am successfully able to run z3 through pySMT in windows.
I am also able to build successfully the python bindings for MATHSAT which includes DLLs,object and lib files for MATHSAT and also contains MATHSAT.py..Still when I am running my example.py..it is giving an error "NoSolverAvailable" . I checked using the command --check., It is depicting MATHSat is not installed .
Am I missing some file in Python bindings or the issue is something else. Please help me.

**Comment by mikand** [comment]
@KritikaA Unfortunately running the MathSAT python bindings on windows is not so easy. If you have a look in the MathSAT zip file, you can see that there is a `setup.py` file in the `python` directory (also see the `README` file there). Ideally, you should run this file (as a normal distutils file) to *compile* the python bindings of MathSAT, but you will need quite a lot of dependencies... So you probably do not have installed the python bindings of MathSAT (you can try to execute `import mathsat` in a python interpreter and see if it succeeds).

As of now, we have not managed to automatically compile the MathSAT python bindings under windows yet. Z3 is the only solver that currently works under windows.

**Comment by KritikaA** [comment]
Thanks..for the quick reply..

**Comment by bellert** [comment]
Are there any special installation instructions for Z3 on Windows? I've installed it many times on Ubuntu with no problems, but when I try to do it on Windows, I get:
```
pysmt-install --check
Installed Solvers:
  msat      False (None)              Not in Python's path!
  z3        False (None)
  cvc4      False (None)              Not in Python's path!
  yices     False (None)              Not in Python's path!
  btor      False (None)              Not in Python's path!
  picosat   False (None)              Not in Python's path!
  bdd       False (None)              Not in Python's path!

Solvers: z3
Quantifier Eliminators: z3, shannon
UNSAT-Cores: z3
Interpolators: z3
```
Note that "Installed Solvers: z3" says "False (none), but the "Not in Python's path!" warning is gone and it is listed below under "Solvers."

When trying to use it in a Python program that runs successfully on Ubuntu, I get a traceback ending in the following:
```
  File "C:\Program Files\Python36\lib\site-packages\pysmt\shortcuts.py", line 817, in Solver
    **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\pysmt\factory.py", line 444, in Solver
    **options)
  File "C:\Program Files\Python36\lib\site-packages\pysmt\factory.py", line 100, in get_solver
    **options)
  File "C:\Program Files\Python36\lib\site-packages\pysmt\solvers\z3.py", line 146, in __init__
    self.z3 = z3.SolverFor(str(logic))
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3.py", line 6399,in Solver
For
    ctx = _get_ctx(ctx)
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3.py", line 220, in _get_ctx
    return main_ctx()
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3.py", line 215, in main_ctx
    _main_ctx = Context()
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3.py", line 160, in __init__
    conf = Z3_mk_config()
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3core.py", line 1301, in Z3_mk_config
    _lib = lib()
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3core.py", line 23, in lib
    raise Z3Exception("init(Z3_LIBRARY_PATH) must be invoked before using Z3-python")
z3.z3types.Z3Exception: init(Z3_LIBRARY_PATH) must be invoked before using Z3-python
Exception ignored in: <bound method Context.__del__ of <z3.z3.Context object at0x000000000BD00710>>
Traceback (most recent call last):
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3.py", line 180, in __del__
    self.lib.Z3_del_context(self.ctx)
AttributeError: 'Context' object has no attribute 'lib'
```

**Comment by marcogario** [comment]
The difference in messages in pysmt-install is due to thr fact that the python module is found but some othet issue exists. This us further shown by the exception that you get.

Are you running master? Did you run pysmt-install --env? Z3 on windows for python 3.6 is part of our CI, so I expect this to work. You can take a look at https://github.com/pysmt/pysmt/blob/master/appveyor.yml to see how we install it. 
Please let me know if this does not solve the problem.

**Comment by bellert** [comment]
Thanks for the quick replies!

@marcogario, I got a chance to try (again) running master. @mikand, this set the `PATH` variable as well as the `PYTHONPATH` variable. I was roughly following the install sequence done by the Appveyor script, but now I have made sure to execute the exact commands in https://github.com/pysmt/pysmt/blob/master/appveyor.yml and compare my output to https://ci.appveyor.com/project/pysmt/pysmt/build/job/7mhys3r4k7chtey4 (python3, 64-bit). Beforehand, I made sure to not have pysmt or any of its dependencies installed and to wipe out the `.smt_solvers` folder in my user directory.

This is what I got:
```
(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>pip install .
Processing c:\users\bellert\documents\pysmt-master\pysmt-master
  Requirement already satisfied (use --upgrade to upgrade): PySMT==0.7.1.dev1 from file:///C:/Users/bellert/Documents/py
smt-master/pysmt-master in c:\users\bellert\documents\pysmt-master\pysmt-master
Collecting six (from PySMT==0.7.1.dev1)
  Using cached six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: PySMT
  Running setup.py bdist_wheel for PySMT ... done
  Stored in directory: C:\Users\bellert\AppData\Local\pip\Cache\wheels\84\81\7e\5014832cfa67ce0375cc4e8e0cf74fcf1d605bd1
1880001881
Successfully built PySMT
Installing collected packages: six
Successfully installed six-1.11.0

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>appveyor.bat

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>REM Check that we have the expected version and architecture
for Python

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>python --version
Python 3.6.4

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>python -c "import struct; print(struct.calcsize('P') * 8)"
64

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>pip install -r dev-requirements.txt
Collecting nose (from -r dev-requirements.txt (line 1))
  Using cached nose-1.3.7-py3-none-any.whl
Requirement already satisfied: wheel in c:\users\bellert\documents\env\lib\site-packages (from -r dev-requirements.txt (
line 2))
Requirement already satisfied: six in c:\users\bellert\documents\env\lib\site-packages (from -r dev-requirements.txt (li
ne 3))
Installing collected packages: nose
Successfully installed nose-1.3.7

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>REM Update setputools

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>pip install --upgrade setuptools
Requirement already up-to-date: setuptools in c:\users\bellert\documents\env\lib\site-packages

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>REM Install the solvers

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>python install.py --z3
This script allows you to install the solvers supported by pySMT.

By executing this script, you confirm that you have read and agreed
with the licenses of each solver.

Notice: the installation process might require building tools
        (e.g., make and gcc).

Continue? [Y]es/[N]o: Y
Downloading: C:\Users\bellert\.smt_solvers\z3\z3-4.5.1.082936bca6fb-x64-win.zip Bytes: 12278298
100.0%

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>REM Set and check the pythonpath

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>python install.py --env  1>bindings_path.bat

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>call ./bindings_path.bat

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>set PYTHONPATH=C:\Users\bellert\.smt_solvers\python-bindings-
3.6;C:\Users\bellert\.smt_solvers\python-bindings-3.6;

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>set PATH=C:\Users\bellert\.smt_solvers\python-bindings-3.6;C:
\Users\bellert\Documents\env\Scripts;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86
)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Wind
ows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon
\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;;C:\Program Files\
Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Prog
ram Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C
:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Common Files\Lenovo;C:
\Program Files\CMake\bin;C:\Program Files\dotnet\

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>ECHO "PythonPath=C:\Users\bellert\.smt_solvers\python-binding
s-3.6;C:\Users\bellert\.smt_solvers\python-bindings-3.6;"
"PythonPath=C:\Users\bellert\.smt_solvers\python-bindings-3.6;C:\Users\bellert\.smt_solvers\python-bindings-3.6;"

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>ECHO "Path=C:\Users\bellert\.smt_solvers\python-bindings-3.6;
C:\Users\bellert\Documents\env\Scripts;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x
86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Wi
ndows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
on\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;;C:\Program File
s\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Pr
ogram Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engin
e Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64
;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Common Files\Lenovo;
C:\Program Files\CMake\bin;C:\Program Files\dotnet\"
"Path=C:\Users\bellert\.smt_solvers\python-bindings-3.6;C:\Users\bellert\Documents\env\Scripts;C:\Program Files\Python36
\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Wi
ndows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Wi
Fi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Fil
es\ThinkPad\Bluetooth Software\syswow64;;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Fil
es\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DA
L;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin
\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\SWTOO
LS\ReadyApps;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files\CMake\bin;C:\Program Files\dotnet\"

(env) C:\Users\bellert\Documents\pysmt-master\pysmt-master>python install.py --check
Installed Solvers:
Traceback (most recent call last):
  File "C:\Users\bellert\Documents\pysmt-master\pysmt-master\pysmt\cmd\check_version.py", line 74, in <module>
    version = check_version(module)
  File "C:\Users\bellert\Documents\pysmt-master\pysmt-master\pysmt\cmd\check_version.py", line 23, in check_version
    (major, minor, ver, _) = z3.get_version()
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3.py", line 81, in get_version
    Z3_get_version(major, minor, build, rev)
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3core.py", line 4641, in Z3_get_version
    _lib = lib()
  File "C:\Users\bellert\.smt_solvers\python-bindings-3.6\z3\z3core.py", line 23, in lib
    raise Z3Exception("init(Z3_LIBRARY_PATH) must be invoked before using Z3-python")
z3.z3types.Z3Exception: init(Z3_LIBRARY_PATH) must be invoked before using Z3-python
Error while checking z3
  msat      False (None)              Not in Python's path!
  cvc4      False (None)              Not in Python's path!
  z3        False (None)
  yices     False (None)              Not in Python's path!
  btor      False (None)              Not in Python's path!
  picosat   False (None)              Not in Python's path!
  bdd       False (None)              Not in Python's path!

Solvers: z3
Quantifier Eliminators: z3, shannon, selfsub
UNSAT-Cores: z3
Interpolators: z3
```

The `z3.get_version()` call is failing.

**Comment by mikand** [comment]
This is very odd. 

One thing you can try is to install Z3 manually:
- wipe the `.smt_solvers` drirectory
- download the z3 nightly from here: https://github.com/pysmt/Z3bin/blob/master/nightly/z3-4.5.1.082936bca6fb-x64-win.zip
- create a directory `z3-python-bindings` somewhere and add it to the `PYTHONPATH` and to the PATH
- copy the directory `bin/python/z3` and all its contents into `z3-python-bindings`
- copy all the dlls in `bin` in `z3-python-bindings`

At this point you should be able to execute:
```
$ python3
>>> import z3
>>> print z3.get_version()
```
If this works, pysmt will be able to use this installation of z3 as long as it is in the `PYTHONPATH`. If it doesn't it means that for some reason this release of Z3 does not work on your system. 

NOTE: maybe the problem is that we only copy the `libz3.dll` but on your system you do not have some of its dependencies installed. Let us know if you manage to get Z3 working this way so that we can update the install script.

**Comment by bellert** [comment]
@mikand, thanks for the detailed directions!

I followed what you outlined and I was able to get Z3 to print out it's version:

```python
>>> import z3
>>> print(z3.get_version())
(4, 5, 1, 7161)
```

When I do `pysmt-install --check`, I get the expected:

```
Installed Solvers:
  msat      False (None)              Not in Python's path!
  cvc4      False (None)              Not in Python's path!
  z3        True (4.5.1)
  yices     False (None)              Not in Python's path!
  btor      False (None)              Not in Python's path!
  picosat   False (None)              Not in Python's path!
  bdd       False (None)              Not in Python's path!

Solvers: z3
Quantifier Eliminators: z3, shannon, selfsub
UNSAT-Cores: z3
Interpolators: z3
```

But when I run my script (that works on Ubuntu), I get a traceback ending in:

```
  File "C:\Users\bellert\Documents\env\lib\site-packages\pysmt\shortcuts.py", line 817, in Solver
    **kwargs)
  File "C:\Users\bellert\Documents\env\lib\site-packages\pysmt\factory.py", line 444, in Solver
    **options)
  File "C:\Users\bellert\Documents\env\lib\site-packages\pysmt\factory.py", line 100, in get_solver
    **options)
  File "C:\Users\bellert\Documents\env\lib\site-packages\pysmt\solvers\z3.py", line 146, in __init__
    self.z3 = z3.SolverFor(str(logic))
  File "C:\Users\bellert\Documents\z3-python-bindings\z3\z3.py", line 6401, in SolverFor
    return Solver(Z3_mk_solver_for_logic(ctx.ref(), logic), ctx)
  File "C:\Users\bellert\Documents\z3-python-bindings\z3\z3core.py", line 5294, in Z3_mk_solver_for_logic
    raise Z3Exception(_lib.Z3_get_error_msg(a0, err))
z3.z3types.Z3Exception: b"logic 'QF_UFLIRA' is not recognized"
```

**Comment by mikand** [comment]
OK, so it seems that the installer needs to be fixed to copy all the DLLs under windows.

Your second problem is wired. Are the installed versions of Z3 on Windows and Ubuntu the same? 

Also, can you try running the pysmt tests?
From the pysmt directory, you can run
```
$ python3 -mnose -v pysmt
```

**Comment by bellert** [comment]
@mikand, good call on checking the version. I see that pysmt's master has been updated to install version 4.5 of Z3 (https://github.com/pysmt/pysmt/commit/ab17a36b4c71023b61c122a141a3f94f4bededd5#diff-7acb7918037e706c3bdcf56322cfa39cR36), while the latest on PyPI installs version 4.4 of Z3. I tried this workflow back on my Ubuntu machine and got the same error I was getting on Windows, leading me to conclude this is a Z3 error.

Back on the Windows machine, I grabbed https://github.com/pysmt/Z3bin/blob/master/releases/z3-4.4.1-x64-win.zip and updated my path to include the contents of this `bin\` directory. Success! I also noted that Z3 has been changing it's directory structure lately, which may be leading to some of these errors if they don't have all the plumbing figured out on their end.

https://github.com/pysmt/Z3bin/blob/master/releases/z3-4.4.1-x64-win.zip:
```
bin\
  *.dll
  *.py
  *.pyc
  __pycache__\
    *.cpython-36.pyc
```

https://github.com/pysmt/Z3bin/blob/master/nightly/z3-4.5.1.082936bca6fb-x64-win.zip:
```
bin\
  *.dll
  python\
    z3\
      *.py
      __pycache__\
        *cpython-36.pyc
```

https://github.com/pysmt/Z3bin/blob/master/releases/z3-4.6.0-x64-win.zip:
```
bin\
  *.dll
  python\
    z3\
      *.py
      *.pyc
```

I also tried with version 4.6. Note that there are two groups of `.pyc` files: ones that end in `cpython-36` and those that don't. In the nightly link that you sent me, the `cpython-36` ones are there, but the others aren't. And in the 4.6 version I tried, the `cpython-36` ones aren't there, but the others are. Only the 4.4 version (out of the versions I tried) has all of these files.

So, as far as a workable solution for users, what do you suggest? It looks like I need the latest changes you've made in https://github.com/pysmt/pysmt/commit/ef882d0a124f9e9ae6b124261ec67ca546c55564, so that all the `.dll`s are copied and `PATH` is set in addition to `PYTHONPATH`, but I also need version 4.4 of Z3. I'm not sure what I'm doing differently that's causing 4.5 to fail on both Ubuntu and Windows, while you're continuous integration scripts are passing.

**Comment by mikand** [comment]
@bellert Sorry for the latency, it's a busy period.

Thank a lot for taking the time to analyze this issue!

- On our side we shall try to upgrade pysmt master to z3-4.6.0 ASAP as it is a stable release (we are using a nightly). 
- To fix your issue, I tried to come up with a patch (it seems from your logs that we are catching the wrong exception here: https://github.com/pysmt/pysmt/blob/master/pysmt/solvers/z3.py#L148). Can you try to checkout the branch called `fixing_z3_logic_by_name` and see if this fixes the issue?

Thanks again,

Andrea

**Comment by bellert** [comment]
@mikand No worries! Thanks for being so responsive.

I tried `fixing_z3_logic_by_name` (commit 09812b8) and it looks like it fixes my issue on Windows! I'll try incorporating this particular commit into my installation process and double check that it works on all systems from scratch.

:+1:

**Comment by mikand** [comment]
@bellert Unless you encountered any issue with the fix, I'm going to merge it to master.

**Comment by bellert** [comment]
@mikand I do believe it solved the problem and is safe to merge. Unfortunately when my colleague tried to do `pysmt-install --z3`, the download just hung there making no progress. It created the `.smt_solvers` folder, but nothing was downloaded and the percentage didn't show up in the terminal. This makes it difficult to debug if it is a related issue or not. We just ended up killing the process and haven't had time to do any further tests.

Windows machines are somewhat scarce around here. Hopefully next week another coworker will be able to try it, but some other more pressing issues have come up. Thanks for your continued support!
