### ISSUE TITLE
pysmt-install crashes if git is not installed

### ISSUE THREAD

**Issue by agriggio** [pysmt/pysmt#389]
```
alb@alb-VirtualBox:~$ pysmt-install -h
Traceback (most recent call last):
  File "/home/alb/.local/bin/pysmt-install", line 11, in <module>
    sys.exit(main())
  File "/home/alb/.local/lib/python2.7/site-packages/pysmt/cmd/install.py", line 170, in main
    options = parse_options()
  File "/home/alb/.local/lib/python2.7/site-packages/pysmt/cmd/install.py", line 108, in parse_options
    version='%(prog)s {version}'.format(version=git_version()))
  File "/home/alb/.local/lib/python2.7/site-packages/pysmt/__init__.py", line 40, in git_version
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by mikand** [comment]
Fixed in PR #390
