### ISSUE TITLE
Parsing error.

### ISSUE THREAD

**Issue by alexeyignatiev** [pysmt/pysmt#446]
Hi guys,

```SmtLibParser()``` fails to parse the following formula:
```
(declare-fun v1 () Bool)
(declare-fun v2 () Bool)
(declare-fun v3 () (_ BitVec 32))
(define-fun v4 () (_ BitVec 32) (ite v1 (bvadd (ite v2 #x00000001 #x00000000) #x00000001) v3))
(declare-fun v5 () (_ BitVec 32))
(define-fun v6 () (_ BitVec 32) (ite v1 v4 v5))
```
When I execute a simple script
```python
from pysmt.smtlib.parser import SmtLibParser

parser = SmtLibParser()
script = parser.get_script_fname('test.smt2')
```
I get the following error:
```
aign@caelum:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    script = parser.get_script_fname('test.smt2')
  File "/Users/aign/.local/lib/python2.7/site-packages/PySMT-0.6.2.dev1-py2.7.egg/pysmt/smtlib/parser.py", line 823, in get_script_fname
    return self.get_script(script)
  File "/Users/aign/.local/lib/python2.7/site-packages/PySMT-0.6.2.dev1-py2.7.egg/pysmt/smtlib/parser.py", line 803, in get_script
    for cmd in self.get_command_generator(script):
  File "/Users/aign/.local/lib/python2.7/site-packages/PySMT-0.6.2.dev1-py2.7.egg/pysmt/smtlib/parser.py", line 817, in get_command_generator
    for cmd in self.get_command(tokens):
  File "/Users/aign/.local/lib/python2.7/site-packages/PySMT-0.6.2.dev1-py2.7.egg/pysmt/smtlib/parser.py", line 987, in get_command
    yield fun(current, tokens)
  File "/Users/aign/.local/lib/python2.7/site-packages/PySMT-0.6.2.dev1-py2.7.egg/pysmt/smtlib/parser.py", line 1089, in _cmd_define_fun
    ebody = self.get_expression(tokens)
  File "/Users/aign/.local/lib/python2.7/site-packages/PySMT-0.6.2.dev1-py2.7.egg/pysmt/smtlib/parser.py", line 783, in get_expression
    raise err
pysmt.exceptions.PysmtTypeError: The formula '(v1 ? ((v2 ? 1_128 : 0_128) + 1_128) : v3)' is not well-formed
```
Z3 seems to have no problem when parsing this formula. Any ideas what causes the issue and whether or not it can be fixed? Thank you.

**Comment by mikand** [comment]
Mmmh, the culprit seems to be `(ite v1 (bvadd (ite v2 #x00000001 #x00000000) #x00000001) v3)` because v3 is declared as a 32 bit integer, while the bvadd is (incorrectly) recognized as a 128 bit operation. 

Are you using the latest master version of pysmt? Recently we found a bug (see #442 and #443) that could be the cause of this problem...

**Comment by alexeyignatiev** [comment]
My apologies, I forgot to check the version of PySMT I was running. It was a few months old. I do not have the issue using the latest master (checked now).
