### ISSUE TITLE
pysmt command fails in Python3

### ISSUE THREAD

**Issue by randomir** [pysmt/pysmt#492]
After clean `pip install pysmt` in a Python 3 virtual env:
```
$ pysmt
Traceback (most recent call last):
  File "/tmp/tmp.QmRID1iOu8/bin/pysmt", line 11, in <module>
    sys.exit(main())
  File "/tmp/tmp.QmRID1iOu8/lib/python3.5/site-packages/pysmt/cmd/shell.py", line 144, in main
    shell = PysmtShell(sys.argv[1:])
  File "/tmp/tmp.QmRID1iOu8/lib/python3.5/site-packages/pysmt/cmd/shell.py", line 63, in __init__
    self.parser = self.get_parser()
  File "/tmp/tmp.QmRID1iOu8/lib/python3.5/site-packages/pysmt/cmd/shell.py", line 80, in get_parser
    choices=['auto'] + self.solvers,
TypeError: can only concatenate list (not "dict_keys") to list
```

**Comment by marcogario** [comment]
Good catch!

Fixed by #493.
