### ISSUE TITLE
RuntimeError: generator raised StopIteration in pysmt.smtlib.parser on python3.7

### ISSUE THREAD

**Issue by chaserhkj** [pysmt/pysmt#520]
Running [the parser example in the tutorial](https://pysmt.readthedocs.io/en/latest/tutorials.html#demonstrates-how-to-perform-smt-lib-parsing-dumping-and-extension) on python 3.7 would yield the following exception:

```
Traceback (most recent call last):
  File "/usr/tmp/env/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 218, in create_generator
    c = next(reader)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hkj/Projects/Research/DryadSynth-Data/t.py", line 46, in <module>
    script = parser.get_script(cStringIO(DEMO_SMTLIB))
  File "/usr/tmp/env/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 834, in get_script
    for cmd in self.get_command_generator(script):
  File "/usr/tmp/env/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 848, in get_command_generator
    for cmd in self.get_command(tokens):
  File "/usr/tmp/env/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 1068, in get_command
    self.consume_opening(tokens, "<main>")
  File "/usr/tmp/env/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 1025, in consume_opening
    p = tokens.consume()
  File "/usr/tmp/env/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 189, in consume_token
    return next(self.generator)
RuntimeError: generator raised StopIteration
```
This is a python3.7-only issue, running on any previous version works fine.

I haven't got the chance to look into it further, but it seems to me that it is related to [this PEP 479](https://www.python.org/dev/peps/pep-0479/) introduced in 3.7.

**Comment by marcogario** [comment]
Thanks for reporting this. Seems like this has escalated with 3.7. We had open iasue #488 about this, and you are right on the PEP479. Would you be able to provide a patch? I can support you in the process.

If not, that is totally ok, we appreciate you talking the time to report this.

**Comment by marcogario** [comment]
I started working on this on the branch https://github.com/pysmt/pysmt/tree/i520_stop_iteration . The main problem is that we were relying on StopIteration bubbling up in many contexts.

In particular, the function Tokenizer.consume_token does not distinguish between the situation in which we *expect* a token to be there or not. Therefore, if the stream was over, this function would raise a StopIteration and this will bubble up the call-stack, typically ending up in one of the top level functions such as get_command_generator.

We need to do two things:
1. Properly propagate the StopIteration when needed (this is mostly done in the branch, see `create_generator`)
2. Change the semantics of `consume_token` to throw syntax errors when we expect to have a token. This is almost always the case, except for `consume_opening` where we expected the function to fail (raising a StopIteration) if there were no more open parenthesis. This behavior is used in order to know if there are more commands in the SMTLIB stream. In the branch I create afunction `consume_enforce` to throw a syntax error. However, I think I got it backwards: the default should be to throw the exception and there should be a way to make a "soft" consume that throws a StopIteration error, and handle this case in the few places were it is truly needed.

**Comment by mikand** [comment]
@marcogario If you want I can try to take a round on this.

**Comment by marcogario** [comment]
Fix in #521. Waiting for merge.
