### ISSUE TITLE
can't instantiate solver

### ISSUE THREAD

**Issue by harper-carroll** [pysmt/pysmt#542]
Hi, I am unable to get pysmt working.

When I run `pysmt-install --check`, I get the error:
```
Traceback (most recent call last):
  File "/Users/harper/anaconda2/bin/pysmt-install", line 11, in <module>
    sys.exit(main())
  File "/Users/harper/anaconda2/lib/python2.7/site-packages/pysmt/cmd/install.py", line 220, in main
    mirror_link=mirror_url)
  File "/Users/harper/anaconda2/lib/python2.7/site-packages/pysmt/cmd/install.py", line 60, in check_installed
    pypath_solvers = get_env().factory.all_solvers()
  File "/Users/harper/anaconda2/lib/python2.7/site-packages/pysmt/environment.py", line 158, in factory
    self._factory = pysmt.factory.Factory(self)
  File "/Users/harper/anaconda2/lib/python2.7/site-packages/pysmt/factory.py", line 86, in __init__
    self._get_available_solvers()
  File "/Users/harper/anaconda2/lib/python2.7/site-packages/pysmt/factory.py", line 252, in _get_available_solvers
    from pysmt.solvers.pico import PicosatSolver
ImportError: No module named pico
```
which is strange, because I am explicitly calling a z3 solver in my code:
`s = pysmt.Solver(name="z3") `
I have fully installed z3 into python2.7/site-packages.

When I try to run `pysmt-install --cvc4` , or try to install any other solver, the command fails on exit status 1, saying:
```
ERROR:  Unable to locate GNU Autoconf.

ERROR:  To prepare the cvc4 build system from scratch,
        at least version 2.61 of GNU Autoconf must be installed.

```
Which is strange, because I downloaded autoconf and the issue does not go away.

How can I fix this? I'd really like to get my pysmt working. Thanks!

**Comment by harper-carroll** [comment]
Also, for a short period pysmt-install --check worked, and it said that z3 was successfully installed. Why is it still trying to get picosat?

**Comment by marcogario** [comment]
Hi, how did you install pysmt?
The error you get is not related to the picosat solver, but to the pySMT side of the interface. Python complains that it cannot find a module within pySMT (pico.py). This should be included in the distribution, so I think there might be an issue with your installation.

For what concerns the installation of cvc4, try to execute autoreconf from the same shell that you are calling pysmt from, just to make sure that the installation worked.
