### ISSUE TITLE
Crash on parsing String formula 

### ISSUE THREAD

**Issue by muchang** [pysmt/pysmt#582]
Hi, I met the crash issue when I wanted to parse a string formula:
python script:
```
from pysmt.smtlib.parser import SmtLibParser
parser = SmtLibParser()
with open("Kaluza/sat/small/1001.corecstrs.readable.smt2","r") as reader:
    script = parser.get_script(reader)
```
logs:
```
Traceback (most recent call last):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 828, in get_expression
    res = fun(*lst)
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "smtfuzzer.py", line 47, in <module>
    script = parser.get_script(reader)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 855, in get_script
    for cmd in self.get_command_generator(script):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 869, in get_command_generator
    for cmd in self.get_command(tokens):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 1108, in get_command
    yield fun(current, tokens)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 1127, in _cmd_assert
    expr = self.get_expression(tokens)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/pysmt/smtlib/parser/parser.py", line 831, in get_expression
    raise NotImplementedError("Unknown function '%s'" % fun)
NotImplementedError: Unknown function 'str.to.re'
```
Fomula:
```
(declare-fun I0_2 () Int)
(declare-fun I0_6 () Int)
(declare-fun PCTEMP_LHS_1 () Int)
(declare-fun PCTEMP_LHS_2 () Int)
(declare-fun T0_2 () String)
(declare-fun T0_6 () String)
(declare-fun T1_2 () String)
(declare-fun T1_6 () String)
(declare-fun T2_2 () String)
(declare-fun T2_6 () String)
(declare-fun T3_2 () String)
(declare-fun T3_6 () String)
(declare-fun T4_2 () String)
(declare-fun T4_6 () String)
(declare-fun T5_2 () String)
(declare-fun T5_6 () String)
(declare-fun T_2 () Bool)
(declare-fun T_3 () Int)
(declare-fun T_5 () Bool)
(declare-fun T_6 () Bool)
(declare-fun T_SELECT_1 () Bool)
(declare-fun T_SELECT_2 () Bool)
(declare-fun var_0xINPUT_15284 () String)
(assert (= T_SELECT_1 (not (= PCTEMP_LHS_1 (- 1)))))
(assert (ite T_SELECT_1 (and (= PCTEMP_LHS_1 (+ I0_2 0))(= var_0xINPUT_15284 (str.++ T0_2 T1_2))(= I0_2 (str.len T4_2))(= 0 (str.len T0_2))(= T1_2 (str.++ T2_2 T3_2))(= T2_2 (str.++ T4_2 T5_2))(= T5_2 "GoogleAdServingTest=")(not (str.in.re T4_2 (re.++   (str.to.re "G" )  (re.++   (str.to.re "o" ) (re.++  (str.to.re "o" ) (re.++  (str.to.re "g" ) (re.++  (str.to.re "l" ) (re.++  (str.to.re "e" ) (re.++  (str.to.re "A" ) (re.++  (str.to.re "d" ) (re.++  (str.to.re "S" ) (re.++  (str.to.re "e" ) (re.++  (str.to.re "r" ) (re.++  (str.to.re "v" ) (re.++  (str.to.re "i" ) (re.++  (str.to.re "n" ) (re.++  (str.to.re "g" ) (re.++  (str.to.re "T" ) (re.++  (str.to.re "e" ) (re.++  (str.to.re "s" ) (re.++  (str.to.re "t" )  (str.to.re "=" )  ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ))) (and (= PCTEMP_LHS_1 (- 1))(= var_0xINPUT_15284 (str.++ T0_2 T1_2))(= 0 (str.len T0_2))(not (str.in.re T1_2 (re.++   (str.to.re "G" )  (re.++   (str.to.re "o" ) (re.++  (str.to.re "o" ) (re.++  (str.to.re "g" ) (re.++  (str.to.re "l" ) (re.++  (str.to.re "e" ) (re.++  (str.to.re "A" ) (re.++  (str.to.re "d" ) (re.++  (str.to.re "S" ) (re.++  (str.to.re "e" ) (re.++  (str.to.re "r" ) (re.++  (str.to.re "v" ) (re.++  (str.to.re "i" ) (re.++  (str.to.re "n" ) (re.++  (str.to.re "g" ) (re.++  (str.to.re "T" ) (re.++  (str.to.re "e" ) (re.++  (str.to.re "s" ) (re.++  (str.to.re "t" )  (str.to.re "=" )  ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )))))
(assert (= T_2 (not (= PCTEMP_LHS_1 (- 1)))))
(assert T_2)
(assert (= T_3 (+ PCTEMP_LHS_1 20)))
(assert (= T_SELECT_2 (not (= PCTEMP_LHS_2 (- 1)))))
(assert (ite T_SELECT_2 (and (= PCTEMP_LHS_2 (+ I0_6 T_3))(= var_0xINPUT_15284 (str.++ T0_6 T1_6))(= I0_6 (str.len T4_6))(= T_3 (str.len T0_6))(= T1_6 (str.++ T2_6 T3_6))(= T2_6 (str.++ T4_6 T5_6))(= T5_6 ";")(not (str.in.re T4_6 (str.to.re ";" )))) (and (= PCTEMP_LHS_2 (- 1))(= var_0xINPUT_15284 (str.++ T0_6 T1_6))(= T_3 (str.len T0_6))(not (str.in.re T1_6 (str.to.re ";" ))))))
(assert (= T_5 (= PCTEMP_LHS_2 (- 1))))
(assert (= T_6 (not T_5)))
(assert T_6)
(check-sat)
```
It seems that pysmt cannot handle str.to.re. The function str.to.re is very usually in string solver benchmark, so maybe I need to implement it by myself.
Do you have any suggestion?

pysmt:0.8.0
ubuntu:18.04
python:3.7

**Comment by marcogario** [comment]
I think str.to.re is not implemented because the regex theory is not implemented. See the following PR https://github.com/pysmt/pysmt/pull/568 , and let us know if this would solve your issue. 

To close the PR we need to do some more work on testing and simplification. If you are interested to contribute, let me know.

**Comment by muchang** [comment]
Thank you @marcogario, it solved my issue. so this issue could be closed. 

BTW, if I am interested to contribute, what should I do?

**Comment by muchang** [comment]
On regex branch, I got another NotImplementedError on this formula:
```
;Theory: S	 Timeout: 30s	 Z3 checking result: sat
(declare-fun PCTEMP_LHS_1 () Bool)
(declare-fun PCTEMP_LHS_3 () String)
(declare-fun PCTEMP_LHS_4_idx_0 () String)
(declare-fun PCTEMP_LHS_5 () String)
(declare-fun T0_24 () String)
(declare-fun T_12 () Bool)
(declare-fun T_13 () Bool)
(declare-fun T_14 () Bool)
(declare-fun T_15 () Bool)
(declare-fun T_16 () Bool)
(declare-fun T_17 () Bool)
(declare-fun T_18 () Bool)
(declare-fun T_2 () Bool)
(declare-fun T_3 () Int)
(declare-fun T_4 () Int)
(declare-fun T_6 () Int)
(declare-fun T_7 () Bool)
(declare-fun T_8 () Bool)
(declare-fun T_9 () Int)
(declare-fun T_a () Bool)
(declare-fun T_b () Bool)
(declare-fun T_c () Int)
(declare-fun T_d () Bool)
(declare-fun T_e () Bool)
(declare-fun var_0xINPUT_250044 () String)
(assert (= T_2 (not PCTEMP_LHS_1)))
(assert T_2)
(assert (= T_3 (str.len var_0xINPUT_250044)))
(assert (= T_4 (div T_3 10)))
(assert (= T_6 (str.len var_0xINPUT_250044)))
(assert (= T_7 (< 70 T_6)))
(assert (= T_8 (not T_7)))
(assert T_8)
(assert (= T_9 (str.len var_0xINPUT_250044)))
(assert (= T_a (< 70 T_9)))
(assert (= T_b (not T_a)))
(assert T_b)
(assert (= T_c (str.len var_0xINPUT_250044)))
(assert (= T_d (< 70 T_c)))
(assert (= T_e (not T_d)))
(assert T_e)
(assert (= PCTEMP_LHS_3 var_0xINPUT_250044))
(assert (= T0_24 PCTEMP_LHS_4_idx_0))
(assert (= T0_24 PCTEMP_LHS_3))
(assert (= T_12 (= PCTEMP_LHS_5 "[object")))
(assert (= T_13 (not T_12)))
(assert T_13)
(assert (= T_15 (not T_14)))
(assert T_15)
(assert (= T_17 (not T_16)))
(assert T_17)
(assert T_18)
(check-sat)
```
The logs
```
Traceback (most recent call last):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 840, in get_expression
    res = fun(*lst)
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 59, in <module>
    script = parser.get_script(reader)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 867, in get_script
    for cmd in self.get_command_generator(script):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 881, in get_command_generator
    for cmd in self.get_command(tokens):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 1122, in get_command
    yield fun(current, tokens)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 1141, in _cmd_assert
    expr = self.get_expression(tokens)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 843, in get_expression
    raise NotImplementedError("Unknown function '%s'" % fun)
NotImplementedError: Unknown function 'div'
```
It seems that `div` isn't implemented in pysmt. But it seems usual in SMTLIB-benchmark:
http://smtlib.cs.uiowa.edu/theories-Ints.shtml

Is there a branch that has the implementation of 'div'?
Thank you!

**Comment by mikand** [comment]
@muchang Unfortunately, we currently have no branch supporting integer division (we have support for real division though), In fact pysmt currently only supports LIA (without integer congruence): http://smtlib.cs.uiowa.edu/logics-all.shtml#LIA .

> BTW, if I am interested to contribute, what should I do?

It is easy! We gladly accept user pull-requests on pysmt and we can offer guidance if there is a particular feature you have in mind that you want to develop! Do you have something in mind?
