### ISSUE TITLE
Two SmtLibParser objects share one symbol

### ISSUE THREAD

**Issue by muchang** [pysmt/pysmt#586]
For the following code which is similar to https://pysmt.readthedocs.io/en/latest/tutorials.html#demonstrates-how-to-perform-smt-lib-parsing-dumping-and-extension :
```
# The last part of the example requires a QF_LIA solver to be installed.
#
#
# This example shows how to interact with files in the SMT-LIB
# format. In particular:
#
# 1. How to read a file in SMT-LIB format
# 2. How to write a file in SMT-LIB format
# 3. Formulas and SMT-LIB script
# 4. How to access annotations from SMT-LIB files
# 5. How to extend the parser with custom commands
#
from six.moves import cStringIO # Py2-Py3 Compatibility

from pysmt.smtlib.parser import SmtLibParser


# To make the example self contained, we store the example SMT-LIB
# script in a string.
DEMO_SMTLIB=\
"""
(set-logic QF_LIA)
(declare-fun p () Int)
(declare-fun q () Int)
(declare-fun x () Bool)
(declare-fun y () Bool)
(define-fun .def_1 () Bool (! (and x y) :cost 1))
(assert (=> x (> p q)))
(check-sat)
(push)
(assert (=> y (> q p)))
(check-sat)
(assert .def_1)
(check-sat)
(pop)
(check-sat)
"""
DEMO_SMTLIB2=\
"""
(set-logic QF_LIA)
(declare-fun p () Bool)
(declare-fun q () Int)
(declare-fun x () Bool)
(declare-fun y () Bool)
(define-fun .def_1 () Bool (! (and x y) :cost 1))
(assert (=> x (> p q)))
(check-sat)
(push)
(assert (=> y (> q p)))
(check-sat)
(assert .def_1)
(check-sat)
(pop)
(check-sat)
"""

# We read the SMT-LIB Script by creating a Parser.
# From here we can get the SMT-LIB script.
parser = SmtLibParser()

# The method SmtLibParser.get_script takes a buffer in input. We use
# cStringIO to simulate an open file.
# See SmtLibParser.get_script_fname() if to pass the path of a file.
script = parser.get_script(cStringIO(DEMO_SMTLIB))
parser = SmtLibParser()
script = parser.get_script(cStringIO(DEMO_SMTLIB2))
```
I created two individual SmtLibParser in the code. However, when the second get_script is called, pysmt crash due to the pysmt.exceptions.PysmtTypeError: 
```
zhangche@ubuntu:~/smtfuzz$ python test.py 
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    script = parser.get_script(cStringIO(DEMO_SMTLIB2))
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 867, in get_script
    for cmd in self.get_command_generator(script):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 881, in get_command_generator
    for cmd in self.get_command(tokens):
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 1122, in get_command
    yield fun(current, tokens)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 1208, in _cmd_declare_fun
    v = self._get_var(var, typename)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/smtlib/parser/parser.py", line 633, in _get_var
    typename=type_name)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/formula.py", line 139, in Symbol
    return self.get_or_create_symbol(name, typename)
  File "/home/zhangche/miniconda3/envs/smtfuzz/lib/python3.7/site-packages/PySMT-0.8.1.dev1-py3.7.egg/pysmt/formula.py", line 133, in get_or_create_symbol
    (name, s.symbol_type(), typename))
pysmt.exceptions.PysmtTypeError: Trying to redefine symbol 'p' with a new type. Previous type was 'Int' new type is 'Bool'
```
It seems that two SmtLibParser objects shared one symbol 'p' causes the crash, but it doesn't make sense.

Is it a feature or a bug in SmtLibParse?

OS: Ubuntu 18.04
python: 3.7
pysmt: 0.8.0

**Comment by marcogario** [comment]
Hi! This is intended, although it might not be what you want for that particular use case.
In pysmt all expressions (and thus symbols) are shared within an environment. Symbols are assumed to be unique based on their name. If you tried to create two symbols with different types, you would get the same error.

You can create a new environment for the second parser, but then you need to decide how to reconcile the two 'b' symbols.
See environment.py to create an environment. Note that you can use it as a context ('with' keyword in python). From shortcuts you can use 'push_env' to obtain a new global environment while preserving the old one. 
If you do not care about the first expression that you read, you can call 'reset_env'.

**Comment by muchang** [comment]
Thank you for your reply!
It solved my problem.
I feed a new environment while creating a new SmtlibParser.
This issue could be closed.
