### ISSUE TITLE
"OverflowError: Python int too large to convert to C long" with yices

### ISSUE THREAD

**Issue by nano-o** [pysmt/pysmt#596]
Hello, the following Python script fails with:
```
Traceback (most recent call last):
  File "test_pysmt.py", line 17, in <module>
    solver.add_assertion(f)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/decorators.py", line 64, in clear_pending_pop_wrap                                                                                                                       
    return f(self, *args, **kwargs)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/solvers/yices.py", line 171, in add_assertion                                                                                                                            
    term = self.converter.convert(formula)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/decorators.py", line 84, in catch_conversion_error_wrap                                                                                                                  
    res = f(*args, **kwargs)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/solvers/yices.py", line 307, in convert                                                                                                                                  
    return self.walk(formula)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/walkers/dag.py", line 106, in walk                                                                                                                                       
    res = self.iter_walk(formula, **kwargs)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/walkers/dag.py", line 98, in iter_walk                                                                                                                                   
    self._process_stack(**kwargs)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/walkers/dag.py", line 91, in _process_stack                                                                                                                              
    self._compute_node_result(formula, **kwargs)
  File "/home/nano/.local/share/virtualenvs/test_env-AitxzBPb/local/lib/python2.7/site-packages/pysmt/walkers/dag.py", line 74, in _compute_node_result                                                                                                                        
    for s in self._get_children(formula)]
OverflowError: Python int too large to convert to C long
```

```
from six.moves import cStringIO
from pysmt.smtlib.parser import SmtLibParser
from pysmt.oracles import get_logic
from pysmt.shortcuts import Solver

with open('./test.smt') as my_file: 
    smt_script = my_file.read()

parser = SmtLibParser()
script = parser.get_script(cStringIO(smt_script))
f = script.get_strict_formula()
print f
target_logic = get_logic(f)
print("Target Logic: %s" % target_logic)

with Solver(logic=target_logic, name='yices') as solver:
    solver.add_assertion(f)
```

```
(set-logic QF_BV)
(declare-fun s0 () (_ BitVec 64))
(define-fun s1 () (_ BitVec 64) #xFFFFFFFFFFFFFFFF)
(define-fun s2 () Bool (= s1 s0))
(assert s2)
(check-sat)
```

**Comment by mikand** [comment]
Hi @nano-o, thanks for reporting this. I just committed a patch in #597.

**Comment by marcogario** [comment]
@nano-o Please note that you can simplify your code by using `pysmt.shortcuts.read_smtlib`, that does exactly the following form your code:
```
with open('./test.smt') as my_file: 
    smt_script = my_file.read()

parser = SmtLibParser()
script = parser.get_script(cStringIO(smt_script))
f = script.get_strict_formula()
```
