### ISSUE TITLE
Tests are failing for the PyPI package

### ISSUE THREAD

**Issue by Pamplemousse** [pysmt/pysmt#608]
When downloading the tar package [from PyPI](https://pypi.org/project/PySMT/#files), [`pysmt/test/configs`](https://github.com/pysmt/pysmt/tree/master/pysmt/test/configs) is missing.

Hence, numerous tests are failing. For example:

```
======================================================================
ERROR: test_read (pysmt.test.test_configuration.TestConfiguration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/PySMT-0.8.0/pysmt/test/test_configuration.py", line 42, in test_read
    configure_environment(self._get_config_path("config1.ini"), env)
  File "/build/PySMT-0.8.0/pysmt/configuration.py", line 56, in configure_environment
    raise PysmtIOError("File '%s' does not exists." % config_filename)
PysmtIOError: File '/build/PySMT-0.8.0/pysmt/test/configs/config1.ini' does not exists.
```

**Comment by marcogario** [comment]
Thanks for reporting. We should probably add a job in the CI to run the tests from pypi.

**Comment by marcogario** [comment]
Fixed in https://github.com/pysmt/pysmt/pull/718 . This is available in the development version or in the next release.
