### ISSUE TITLE
cant install cvc4 on windows 10

### ISSUE THREAD

**Issue by drskuce** [pysmt/pysmt#610]
I am running Win10  64  using Pycharm and installed pystm
I spent several hours trying to get cvc4 working without luck  
 it kept complaining about z3 but I have not chosen any solver yet      why is it looking for z3?
here is the powershell output including pythonpath

PS C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\cmd> python install.py --cvc4
python : Traceback (most recent call last):
At line:1 char:1
+ python install.py --cvc4
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "install.py", line 29, in <module>
    from pysmt.environment import get_env
  File "C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\environment.py", line 25, in <module>
    import pysmt.printers
  File "C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\printers.py", line 24, in <module>
    from pysmt.constants import is_pysmt_fraction, is_pysmt_integer
  File "C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\constants.py", line 186, in <module>
    import z3.z3num
  File "C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\solvers\z3.py", line 29, in <module>
    z3.set_param('model_compress', False)
AttributeError: module 'z3' has no attribute 'set_param'

PS C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\cmd> Get-Childitem env:pythonpath

Name                           Value                                                                                                                          
----                           -----                                                                                                                          
PYTHONPATH                     C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages;C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\solvers              

PS C:\Users\doug\Dropbox\Neo1\venv\Lib\site-packages\pysmt\cmd> 

any help would be appreciated

thanks

Doug S

**Comment by mikand** [comment]
Closing as stale. The traceback is `module 'z3' has no attribute 'set_param'`,
which came from a z3 build predating 4.5; master installs z3 4.15.0 (e1a1b6e7,
#808). The related Windows `get_logic_by_name` failure from that era was fixed
in #473. The z3 import in `pysmt/solvers/z3.py` is also no longer reached the
way it was in that version of the code.

Windows solver installation is tracked in #328. Please open a new issue if
`pysmt-install --cvc5` (cvc5 replaced CVC4, see #677) fails on a current
Windows.
