### ISSUE TITLE
PysmtTypeError: Trying to redefine symbol 'A' with a new type. Previous type was 'S{Bool}' new type is 'Bool'

### ISSUE THREAD

**Issue by PatrickTrentin88** [pysmt/pysmt#633]
There appears to be a problem with the Unit Test `pysmt.test.smtlib.test_parser_extensibility.TestParserExtensibility`:

```
~$  ./run_tests.sh 
test_griggio (pysmt.test.smtlib.test_griggio.TestSmtLibParserGriggio) ... ok
test_basic (pysmt.test.smtlib.test_parser_extensibility.TestParserExtensibility) ... ERROR

======================================================================
ERROR: test_basic (pysmt.test.smtlib.test_parser_extensibility.TestParserExtensibility)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/qian/dev.work/github.com/pysmt/pysmt/test/smtlib/test_parser_extensibility.py", line 109, in test_basic
    self.smt_parser.get_script(cStringIO(txt))
  File "/data/qian/dev.work/github.com/pysmt/pysmt/smtlib/parser/parser.py", line 855, in get_script
    for cmd in self.get_command_generator(script):
  File "/data/qian/dev.work/github.com/pysmt/pysmt/smtlib/parser/parser.py", line 869, in get_command_generator
    for cmd in self.get_command(tokens):
  File "/data/qian/dev.work/github.com/pysmt/pysmt/smtlib/parser/parser.py", line 1108, in get_command
    yield fun(current, tokens)
  File "/data/qian/dev.work/github.com/pysmt/pysmt/smtlib/parser/parser.py", line 1194, in _cmd_declare_fun
    v = self._get_var(var, typename)
  File "/data/qian/dev.work/github.com/pysmt/pysmt/smtlib/parser/parser.py", line 621, in _get_var
    typename=type_name)
  File "/data/qian/dev.work/github.com/pysmt/pysmt/formula.py", line 143, in Symbol
    return self.get_or_create_symbol(name, typename)
  File "/data/qian/dev.work/github.com/pysmt/pysmt/formula.py", line 137, in get_or_create_symbol
    (name, s.symbol_type(), typename))
PysmtTypeError: Trying to redefine symbol 'A' with a new type. Previous type was 'S{Bool}' new type is 'Bool'

----------------------------------------------------------------------
Ran 2 tests in 0.082s

FAILED (errors=1)
```

**Comment by mikand** [comment]
@PatrickTrentin88 The issue is due to multiprocessing in nosetests. Have a look at #637 for a fix.
