### ISSUE TITLE
Some polynomials take an extremely long time to solve.

### ISSUE THREAD

**Issue by josiahblaisdell** [pysmt/pysmt#648]
Hi, I have found that the following serialized problem takes a very long time to solve and I do not understand why... There are 3 variables, x0, x1, x2 and there are 6 constraints.  I have several other examples that work very quickly, but this one hangs. I have other examples (with 4 variables) that hang indefinitely. I am not sure if this is by design or if there is some theory I am missing, but it seems like this shouldn't take so long to solve.

I am using the z3 library. 

                        ((-0.83 <= ((x0 * x0 * -0.105) + (x0 * x1 * 0.227) + (x0 * x2 * 0.357) + (x0 * 0.818) + (x1 * x1 * -0.777) + (x1 * x2 * -0.37) + (x1 * -0.061) + (x2 * x2 * -0.758) + (x2 * 0.708) + -0.279)) 
                        & (((x0 * -0.008) + (x1 * -0.002) + (x2 * -0.186) + 0.353) < 0.027)
                        & (-0.12 <= ((x0 * -0.008) + (x1 * -0.002) + (x2 * -0.186) + 0.353))
                        & (((x0 * 0.241) + (x1 * -0.037) + (x2 * -0.027) + 0.299) < 0.316)
                        & (-0.226 <= ((x0 * 0.241) + (x1 * -0.037) + (x2 * -0.027) + 0.299))
                        & (((x0 * 0.057) + (x1 * -0.065) + (x2 * 0.326) + -0.201) < 0.86)
                        & (-0.973 <= ((x0 * 0.057) + (x1 * -0.065) + (x2 * 0.326) + -0.201)))

**Comment by josiahblaisdell** [comment]
The 4 variable problem that runs indefinitely is:
((((-5314247560297185/9007199254740992 <= ((-4944952390852805/9007199254740992 * x0) + (5620492334958379/72057594037927936 * x1) + (-1098878309078401/9007199254740992 * x2) + (3602879701896397/9007199254740992 * x3) + -8070450532247929/1152921504606846976)) & (((-4944952390852805/9007199254740992 * x0) + (5620492334958379/72057594037927936 * x1) + (-1098878309078401/9007199254740992 * x2) + (3602879701896397/9007199254740992 * x3) + -8070450532247929/1152921504606846976) < 3422735716801577/36028797018963968)) & ((-5710564327505789/9007199254740992 <= ((-6908521828386341/9007199254740992 * x0) + (-8322652111380677/36028797018963968 * x1) + (3260606130216239/4503599627370496 * x2) + (-3242591731706757/72057594037927936 * x3) + -3548836506367951/9007199254740992)) & (((-6908521828386341/9007199254740992 * x0) + (-8322652111380677/36028797018963968 * x1) + (3260606130216239/4503599627370496 * x2) + (-3242591731706757/72057594037927936 * x3) + -3548836506367951/9007199254740992) < 8178536923304821/18014398509481984)) & ((-6106881094714393/18014398509481984 <= ((7512004178453987/9007199254740992 * x0) + (-308496574474879/2251799813685248 * x1) + (6124895493223875/18014398509481984 * x2) + (5188146770730811/72057594037927936 * x3) + 7782220156096217/288230376151711744)) & (((7512004178453987/9007199254740992 * x0) + (-308496574474879/2251799813685248 * x1) + (6124895493223875/18014398509481984 * x2) + (5188146770730811/72057594037927936 * x3) + 7782220156096217/288230376151711744) < 1080863910568919/72057594037927936))) & (-1643813863990231/4503599627370496 <= ((8493788897220755/9007199254740992 * (x0 * x0)) + (-1272266894732165/2251799813685248 * (x0 * x1)) + (-7656119366529843/18014398509481984 * (x0 * x2)) + (-6296032279063953/9007199254740992 * (x0 * x3)) + (6106881094714393/18014398509481984 * x0) + (-7566047373982433/9007199254740992 * (x1 * x1)) + (8178536923304821/18014398509481984 * (x1 * x2)) + (3530822107858469/72057594037927936 * (x1 * x3)) + (-7674133765039325/9007199254740992 * x1) + (4566650022153683/9007199254740992 * (x2 * x2)) + (3332663724254167/18014398509481984 * (x2 * x3)) + (4620693217682129/9007199254740992 * x2) + (-6088866696204911/36028797018963968 * (x3 * x3)) + (6350075474592399/9007199254740992 * x3) + -8709961679334539/9007199254740992)))

**Comment by josiahblaisdell** [comment]
If I press "ctrl-c" to stop the solver, I get the following error:

We've got an error while stopping in unhandled exception: <class 'pysmt.exceptions.SolverReturnedUnknownResultError'>.
Traceback (most recent call last):
  File "c:\Users\josia\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy\_vendored\pydevd\pydevd.py", line 1965, in do_stop_on_unhandled_exception
    self.do_wait_suspend(thread, frame, 'exception', arg, is_unhandled_exception=True)
  File "c:\Users\josia\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy\_vendored\pydevd\pydevd.py", line 1830, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\josia\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy\_vendored\pydevd\pydevd.py", line 1862, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\josia\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\josia\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\josia\.vscode\extensions\ms-python.python-2020.5.80290\pythonFiles\lib\python\debugpy\no_wheels\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\src\courses\CS517\sat-fish-py\sat_fish_tester.py", line 51, in <module>
    out = sat_fish_processor.processor(filename)
  File "d:\src\courses\CS517\sat-fish-py\sat_fish_processor.py", line 126, in processor
    models.append(get_model(p0))
  File "C:\Users\josia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pysmt\shortcuts.py", line 1021, in get_model
    return env.factory.get_model(formula,
  File "C:\Users\josia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pysmt\factory.py", line 474, in get_model
    if solver.solve():
  File "C:\Users\josia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pysmt\solvers\solver.py", line 376, in solve
    res = self._solve(assumptions=assumptions)
  File "C:\Users\josia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pysmt\decorators.py", line 64, in clear_pending_pop_wrap
    return f(self, *args, **kwargs)
  File "C:\Users\josia\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pysmt\solvers\z3.py", line 214, in _solve
    raise SolverReturnedUnknownResultError

**Comment by marcogario** [comment]
:wave: The problem you are trying to solve is in QF_NRA. I think the procedure that z3 is using is incomplete, so you are not guaranteed completion. For reference, it would be good if you could output the SMTLIB problem and try directly calling z3 or yices on it. There might be some setting to improve the selection of algorithm used to solve this.
