### ISSUE TITLE
Symbolic String Array Elements

### ISSUE THREAD

**Issue by bdrodes** [pysmt/pysmt#650]
In z3 I can have string index and value arrays and access symbolic elements, but trying something similar in pysmt results in an exception. Details below. I'm new to pysmt, but given I know z3 can handle these constraints, is there some simple way to open up pysmt to this capability? 

Details as follows:

In my use case I have arrays with String indices and values. In z3 I might do something like this:

```
In [2]: a = Array("a", StringSort(), StringSort())
In [3]: a = Store(a, StringVal("0"), String("dummy"))
In [4]: solver = z3.Solver()
In [5]: solver.add(String("test") == a[String("0")])
In [6]: solver.check()
Out[6]: sat
In [7]: solver.model()
Out[7]: [a = K(String, ""), dummy = "", 0 = "", test = ""]
```

Similarly in pysmt I tried this:

```
a = Symbol("a", ArrayType(STRING, STRING))
dummy = Symbol("dummy", STRING)
a = Store(a, String('0'), dummy)
# This fails
m = get_model(Equals(Symbol("test", STRING), Select(a, String('0'))))
print(m)

```

Producing the following exception:

```
Traceback (most recent call last):
  File "pysmt_tests.py", line 394, in <module>
    m = get_model(Equals(Symbol("test", STRING), Select(a, String('0'))))
  File "/home/bdrodes/.virtualenvs/dev/lib/python3.7/site-packages/pysmt/shortcuts.py", line 1024, in get_model
    logic=logic)
  File "/home/bdrodes/.virtualenvs/dev/lib/python3.7/site-packages/pysmt/factory.py", line 469, in get_model
    logic = get_logic(formula, self.environment)
  File "/home/bdrodes/.virtualenvs/dev/lib/python3.7/site-packages/pysmt/oracles.py", line 522, in get_logic
    return get_closer_pysmt_logic(logic)
  File "/home/bdrodes/.virtualenvs/dev/lib/python3.7/site-packages/pysmt/logics.py", line 801, in get_closer_pysmt_logic
    return get_closer_logic(PYSMT_LOGICS, target_logic)
  File "/home/bdrodes/.virtualenvs/dev/lib/python3.7/site-packages/pysmt/logics.py", line 795, in get_closer_logic
    raise NoLogicAvailableError("Logic %s is not supported" % logic)
pysmt.exceptions.NoLogicAvailableError: Logic Detected Logic is not supported
```

**Comment by marcogario** [comment]
This seems like either a bug in the logic detection, or Z3 not being decorated with a logic combining both arrays and strings. 

I assume you were using the branch with Z3 string support. That branch needs probably an update, but otherwise, I expect this to work https://github.com/pysmt/pysmt/pull/260.

**Comment by bdrodes** [comment]
I should've updated this thread. After I submitted this report several months ago, I went in and manually modified the theories logic include some of the array-supporting theories I needed (e.g., QF_QSLIA and QF_ASLIRA). I added these to logics.py:

```
QF_ASLIA = Logic(name="QF_ASLIA",
                description=\
                """Extension of LIA including theory of Strings.""",
                integer_arithmetic=True,
                quantifier_free=True,
                uninterpreted=True,
                arrays=True,
                strings=True)

QF_ASLIRA = Logic(name="QF_ASLIRA",
                description=\
                """Extension of LIA including theory of Strings.""",
                real_arithmetic=True,
                integer_arithmetic=True,
                quantifier_free=True,
                uninterpreted=True,
                strings=True,
                arrays=True)
```


In addition, I've since switched to using CVC4 as a primary solver. Strings require CVC4 to specify the strings-exp flag, so after adding these logics I had to update the CVC4Options class to recognize the array logics and set the strings-exp flag accordingly: 

```
    def __call__(self, solver):
        if solver.logic_name == "QF_SLIA" or solver.logic_name == "QF_ASLIA" or solver.logic_name == "QF_ASLIRA":
            self._set_option(solver.cvc4,
                             "strings-exp", "true")
```
