### ISSUE TITLE
TypeError: '<=' not supported between instances of 'str' and 'Logic' (PySMT==0.9.1.dev139)

### ISSUE THREAD

**Issue by danyalette** [pysmt/pysmt#708]
On PySMT==0.9.1.dev139, running one of the examples from the README (below), I get the following error: 

```
Traceback (most recent call last):
  File "/home/user/del.py", line 6, in <module>
    with Portfolio(["cvc4",
  File "/home/user/.local/lib/python3.9/site-packages/pysmt/shortcuts.py", line 977, in Portfolio
    return pf.Portfolio(solvers_set=solvers_set,
  File "/home/user/.local/lib/python3.9/site-packages/pysmt/solvers/portfolio.py", line 80, in __init__
    all_solvers = set(self.environment.factory.all_solvers(logic=logic))
  File "/home/user/.local/lib/python3.9/site-packages/pysmt/factory.py", line 381, in all_solvers
    return self._filter_solvers(self._all_solvers, logic=logic)
  File "/home/user/.local/lib/python3.9/site-packages/pysmt/factory.py", line 361, in _filter_solvers
    if logic <= l:
TypeError: '<=' not supported between instances of 'str' and 'Logic'
```

Here is file I was running: 

```python
from pysmt.shortcuts import Portfolio, Symbol, Not

x, y = Symbol("x"), Symbol("y")
f = x.Implies(y)

with Portfolio(["cvc4",
                "yices"],
               logic="QF_UFLIRA",
               incremental=False,
               generate_models=False) as s:
  s.add_assertion(f)
  s.push()
  s.add_assertion(x)
  res = s.solve()
  v_y = s.get_value(y)
  print(v_y) # TRUE

  s.pop()
  s.add_assertion(Not(y))
  res = s.solve()
  v_x = s.get_value(x)
  print(v_x) # FALSE
```

I am on Ubuntu 21.10, Python 3.9.7, and here is the output from `pysmt-install --check`

```
Installed Solvers:
  msat      True (5.6.1)             Not in Python's path!
  cvc4      True (1.7-prerelease)    
  z3        True (4.8.7)             
  yices     True (2.6.2)             
  btor      True (3.2.1)             
  picosat   True (965)               
  bdd       False (None)              Not in Python's path!

Solvers: z3, cvc4, yices, picosat, btor
Quantifier Eliminators: z3, shannon, selfsub
UNSAT-Cores: z3, btor
Interpolators: 
```

**Comment by mikand** [comment]
Hi @danyalette,

thanks for reporting. This looks like a bug.

As a temporary fix, try to pass the logic object instead of the logic string:
```python
from pysmt.shortcuts import Portfolio, Symbol, Not
from pysmt.logics import QF_UFLIRA
x, y = Symbol("x"), Symbol("y")
f = x.Implies(y)

with Portfolio(["msat",
                "yices"],
               logic=QF_UFLIRA,
               incremental=False,
               generate_models=False) as s:
  s.add_assertion(f)
  s.push()
  s.add_assertion(x)
  res = s.solve()
  v_y = s.get_value(y)
  print(v_y) # TRUE

  s.pop()
  s.add_assertion(Not(y))
  res = s.solve()
  v_x = s.get_value(x)
  print(v_x) # FALSE
```

**Comment by danyalette** [comment]
That resolves it, thanks!
