### ISSUE TITLE
ImportError: No module named shortcuts

### ISSUE THREAD

**Issue by ashfaq92** [pysmt/pysmt#737]
Newly installed `pysmt` on Macbook by:
`pip3 install pysmt`

While trying to run an example code given in README file:
`from pysmt.shortcuts import Symbol, And, Not, is_sat`

The following error is shown:
`
Traceback (most recent call last):
  File "/Volumes/GoogleDrive-102241839393799576524/My Drive/research/testing-parametric-systems/assignment/pysmt.py", line 1, in <module>
    from pysmt.shortcuts import Symbol, And, Not, is_sat
  File "/Volumes/GoogleDrive-102241839393799576524/My Drive/research/testing-parametric-systems/assignment/pysmt.py", line 1, in <module>
    from pysmt.shortcuts import Symbol, And, Not, is_sat
ImportError: No module named shortcuts
`

**Comment by mikand** [comment]
Dear @ashfaq92,

try to rename your script file.

If I understand correctly it is called `pysmt.py`, call it something that does not clash with pysmt, otherwise the `import pysmt.XXX` will search in your own file!

**Comment by ashfaq92** [comment]
Dear @mikand 

renamed to `example.py`, same problem.

**Comment by ashfaq92** [comment]
While trying to print the stacktrace, it has been learned that the error is shown only in the VSCode. In PyCharm CE, it works fine. However, a new error is shown for this code:

`
from pysmt.shortcuts import Symbol, And, Not, is_sat

varA = Symbol("A") # Default type is Boolean
varB = Symbol("B")
f = And(varA, Not(varB))
print(f)

is_sat(f)
`

`
Traceback (most recent call last):
  File "/Volumes/GoogleDrive-102241839393799576524/My Drive/research/testing-parametric-systems/assignment/example.py", line 8, in <module>
    is_sat(f)
  File "/Users/mashfaq/Library/Python/3.8/lib/python/site-packages/pysmt/shortcuts.py", line 1000, in is_sat
    return env.factory.is_sat(formula,
  File "/Users/mashfaq/Library/Python/3.8/lib/python/site-packages/pysmt/factory.py", line 463, in is_sat
    solver = self.Solver(name=solver_name, logic=logic,
  File "/Users/mashfaq/Library/Python/3.8/lib/python/site-packages/pysmt/factory.py", line 437, in Solver
    return self.get_solver(name=name,
  File "/Users/mashfaq/Library/Python/3.8/lib/python/site-packages/pysmt/factory.py", line 91, in get_solver
    self._get_solver_class(solver_list=self._all_solvers,
  File "/Users/mashfaq/Library/Python/3.8/lib/python/site-packages/pysmt/factory.py", line 146, in _get_solver_class
    raise NoSolverAvailableError("No %s is available" % solver_type)
pysmt.exceptions.NoSolverAvailableError: No Solver is available
`

**Comment by ashfaq92** [comment]
From the readme file:

> You can install the latest stable release of pySMT from PyPI:
> 
> `# pip install pysmt`
> this will additionally install the pysmt-install command, that can be used to install the solvers: e.g.,
> 
> `$ pysmt-install --check`


when I try to run the command, I see this error:

`bash: pysmt-install: command not found`

**Comment by mikand** [comment]
Closing as stale; no pySMT defect was identified here.

The two symptoms in the thread point at the installation rather than at pySMT:
the shadowing `pysmt.py` script, and then `pysmt-install: command not found`,
which means the console script directory is not on `PATH` (typically
`~/.local/bin` for a user-site install).

If you still hit this, please open a new issue with the output of
`python3 -m pip show pysmt` and `python3 -c "import pysmt; print(pysmt.__file__)"`.
